export REACT_APP_AUTH0_DOMAIN := dev-kovicniqndmbavnk.us.auth0.com
export REACT_APP_AUTH0_CLIENT_ID :=uKkW1kWwrfHsV3wahKZq6v51XgVJ2R2y
export REACT_APP_AUTH0_AUDIENCE := FinancialManagerAPI
export FINANCE_API := http://localhost:3333


# export REACT_APP_AUTH0_DOMAIN := controlefamiliar-prod.us.auth0.com
# export REACT_APP_AUTH0_CLIENT_ID :=NEluMT72mWTelLrdRBprFoRUbWoLFa1H
# export REACT_APP_AUTH0_AUDIENCE := ControleFamiliarAPI
# export FINANCE_API := https://w830fgiucg.execute-api.us-east-1.amazonaws.com/dev

start:
	npm start

build:
	npm run build