name: Deploy to dev
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy the app'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        stable: 'true'
        go-version: '1.18'
    - name: Build
      run: |
        go mod download && GOOS=linux go build cmd/fm-transaction/main.go && zip deployment.zip main
    - name: Build zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r fm_transaction_latest.zip main
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: fm-dev-transaction
        zip_file: deployment.zip
        handler: main